### Supposing we have filtered and transformed our sentences. Then the next task would be getting feature vector, train different kind of estimators and evaluate them 

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('texts.csv')

In [3]:
df.head()

Text   sentiment
0  যখন মানুষের খুব প্রিয় কেউ তাকে অপছন্দ অবহেলা ...           0
1  আর অনেকদিন পরে সে আগের চেয়েও অনেকবেশী খুশি থা...           1
2                                              আনন্দ           1
3    নিকোটিনের বিষে আমার শরীরের প্রতিটি কোষ অভ্যস্ত            0
4                                           সিগারেট            0

In [4]:
stop = []
with open('stopwords','r') as f:
    for line in f:
        for word in line.split():
            stop.append(word)

In [5]:
def tokenizer(text):
    text = text.split()
    return [w for w in text if w not in stop]

In [6]:
df['Text'].values[0]

'যখন মানুষের খুব প্রিয় কেউ তাকে অপছন্দ অবহেলা কিংবা ঘৃণা করে তখন প্রথম প্রথম মানুষ খুব কষ্ট পায় এবং চায় যে সব ঠিক হয়ে যাক'

In [7]:
tokenizer(df['Text'].values[0])

['মানুষের',
 'প্রিয়',
 'অপছন্দ',
 'অবহেলা',
 'ঘৃণা',
 'প্রথম',
 'প্রথম',
 'মানুষ',
 'কষ্ট',
 'পায়',
 'চায়',
 'হয়ে',
 'যাক']

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
count = CountVectorizer(stop_words=stop,tokenizer=tokenizer)

In [10]:
bag = count.fit_transform(df['Text'].values)

In [11]:
count.vocabulary_

{'অকপট': 0,
 'অকৃতজ্ঞতা': 1,
 'অকৃতজ্ঞতার': 2,
 'অগ্রাধিকার': 3,
 'অজ্ঞের': 4,
 'অত্যাচার': 5,
 'অনাহারে': 6,
 'অনেকদিন': 7,
 'অনেকবেশী': 8,
 'অন্তর্গত': 9,
 'অন্যের': 10,
 'অপকর্মের': 11,
 'অপছন্দ': 12,
 'অপরাধ': 13,
 'অপ্রিয়': 14,
 'অবস্থায়': 15,
 'অবহেলা': 16,
 'অবেলায়': 17,
 'অভিজ্ঞতায়': 18,
 'অভিমান': 19,
 'অভ্যস্ত': 20,
 'অর্থহীন': 21,
 'অশিক্ষিত': 22,
 'অশ্লীল': 23,
 'অসাধুর': 24,
 'অহিংসা': 25,
 'আইনশৃঙ্খলা': 26,
 'আকাইম্যা': 27,
 'আক্রমণের': 28,
 'আগের': 29,
 'আত্নার': 30,
 'আত্মশক্তির': 31,
 'আদব-কায়দাই': 32,
 'আদর': 33,
 'আনন্দ': 34,
 'আনন্দপুর্ন': 35,
 'আপ্যায়ন': 36,
 'আসবে': 37,
 'আসে': 38,
 'ইচ্ছানুযায়ী': 39,
 'ইবাদত': 40,
 'উচিৎ': 41,
 'উত্তম': 42,
 'উদ্রেক': 43,
 'উপভোগ': 44,
 'উৎকৃষ্ট': 45,
 'একজনের': 46,
 'একশো': 47,
 'ওঠো': 48,
 'ওস্তাদের': 49,
 'কতগুলো': 50,
 'কথা': 51,
 'কপট': 52,
 'কম': 53,
 'কমন': 54,
 'করলেই': 55,
 'করুণা': 56,
 'কর্তব্য': 57,
 'কল্পনাশক্তিই': 58,
 'কষ্ট': 59,
 'কাঁদে': 60,
 'কামনা': 61,
 'কামনাও': 62,
 'কারো': 63,
 'কোনই': 64,
 'কোষ': 65,
 'ক্

In [12]:
bag.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
bag.toarray()[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [14]:
from sklearn.feature_extraction.text import TfidfTransformer

In [15]:
tfidf = TfidfTransformer()

In [16]:
tfidf.fit_transform(bag).toarray()[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.26515948,  0.        ,  0.        ,
        0.        ,  0.24504031,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.23076553,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [17]:
df.columns = ['text','sentiment']

In [18]:
X = df['text'].values

In [19]:
y = df['sentiment'].values

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.1,random_state=1)

In [22]:
from sklearn.pipeline import Pipeline

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
count = CountVectorizer(stop_words=stop)

In [27]:
tfidf = TfidfVectorizer(stop_words=stop, tokenizer=tokenizer)

In [28]:
lr_pipe = Pipeline([('vect',tfidf),
                    ('clf',LogisticRegression(random_state=0))])

In [29]:
lr_pipe.fit(X_train,y_train)

Pipeline(steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
  ...nalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])

In [30]:
lr_pipe.score(X_train,y_train)

0.99270072992700731

In [31]:
lr_pipe.score(X_test,y_test)

0.625

In [32]:
lr_pipe.score(X_train,y_train)

0.99270072992700731

In [33]:
X_train[0]

'সত্যের '

In [34]:
import numpy as np

In [35]:
label = {0:'negative',1:'positive'}

In [41]:
X_train[1:2]

array(['হিংসার '], dtype=object)

In [44]:
lr_pipe.predict(X_train[1:2])

array([0])

In [46]:
X_train[0]

'সত্যের '

In [48]:
label[lr_pipe.predict(X_train[0:1])[0]]

'positive'

In [54]:
lr_pipe.predict(X_train[1:2])

array([0])

In [55]:
from sklearn.cross_validation import cross_val_score

In [56]:
scores = cross_val_score(estimator=lr_pipe,X=X_train,y=y_train,cv=10,n_jobs=1)

In [57]:
scores

array([ 0.73333333,  0.53333333,  0.57142857,  0.71428571,  0.5       ,
        0.53846154,  0.76923077,  0.53846154,  0.46153846,  0.53846154])

In [58]:
np.mean(scores)

0.5898534798534798

In [59]:
np.std(scores)

0.10209889919334542

In [60]:
from sklearn.metrics import precision_score

In [61]:
from sklearn.metrics import recall_score, f1_score

In [63]:
y_pred = lr_pipe.predict(X_test)

In [64]:
precision_score(y_true=y_test,y_pred=y_pred)

0.59999999999999998

In [65]:
recall_score(y_true=y_test,y_pred=y_pred)

1.0

In [66]:
f1_score(y_true=y_test,y_pred=y_pred)

0.74999999999999989

In [67]:
from sklearn.metrics import roc_auc_score

In [69]:
roc_auc_score(y_true=y_test,y_score=y_pred)

0.5714285714285714

In [70]:
from sklearn.grid_search import GridSearchCV

In [71]:
param_range = [0.0001,0.001,0.01,0.1,1.0,10.0,100.0,1000.0]

In [72]:
lr_param_grid = [{'clf__C':param_range,
                  'clf__penalty':['l1']},
                 {'clf__C':param_range,
                  'clf__penalty':['l2']}]

In [75]:
lr_gs = GridSearchCV(estimator=lr_pipe,param_grid=lr_param_grid,scoring='accuracy',cv=10,n_jobs=-1)

In [76]:
lr_gs = lr_gs.fit(X_train,y_train)

In [77]:
lr_gs.best_score_

0.5985401459854015

In [78]:
lr_gs.best_params_

{'clf__C': 10.0, 'clf__penalty': 'l2'}

In [79]:
from sklearn.svm import SVC

In [80]:
svc_pipe = Pipeline([('vect',tfidf),
                     ('clf',SVC(random_state=1))])

In [81]:
svc_param_grid = [{'clf__C':param_range,
                   'clf__kernel': ['linear']},
                  {'clf__C':param_range,
                   'clf__gamma':param_range,
                   'clf__kernel': ['rbf']}]

In [83]:
svc_gs = GridSearchCV(estimator=svc_pipe,param_grid=svc_param_grid,scoring='accuracy',cv=10,n_jobs=-1)

In [84]:
svc_gs = svc_gs.fit(X_train,y_train)

In [85]:
svc_gs.best_score_

0.5985401459854015

In [86]:
svc_gs.best_params_

{'clf__C': 1.0, 'clf__kernel': 'linear'}

In [87]:
from sklearn.tree import DecisionTreeClassifier

In [88]:
dt_pipe = Pipeline([('vect',tfidf),
                     ('clf',DecisionTreeClassifier(random_state=0))])

In [93]:
dt_gs = GridSearchCV(estimator=dt_pipe, param_grid=[ {'clf__max_depth': [1, 2, 3, 4, 5, 6, 7, None] }], scoring='accuracy', cv=5)

In [94]:
dt_gs = dt_gs.fit(X_train,y_train)

In [95]:
dt_gs.best_params_

{'clf__max_depth': None}

In [96]:
dt_gs.best_score_

0.5474452554744526

In [97]:
from sklearn.neighbors import KNeighborsClassifier

In [101]:
knn_pipe = Pipeline([('vect',tfidf),
                     ('clf',KNeighborsClassifier())])

In [102]:
knn_pipe.fit(X_train,y_train)

Pipeline(steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
  ...owski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'))])

In [103]:
knn_pipe.score(X_test,y_test)

0.625